# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

name: demo_pipeline

variables:
  var1: value1

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: job_build_gtest
    displayName: 'build google test and publish artifacts'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CMake@1
      inputs:
        workingDirectory: 'cmake_build'
        cmakeArgs: '-DCMAKE_BUILD_TYPE=Release -DBUILD_GMOCK=OFF -DCMAKE_INSTALL_PREFIX=release ..'

    - bash: 'make -j8 VERBOSE=1'
      workingDirectory:  'cmake_build'
      failOnStderr: true
      
    - bash: 'make install'
      workingDirectory:  'cmake_build'
      failOnStderr: true

    - publish: $(Build.SourcesDirectory)/cmake_build/release
      artifact: google_test
      displayName: 'publish google test Azure pipeline artifacts'

    - task: UniversalPackages@0
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.SourcesDirectory)/cmake_build/release'
        vstsFeedPackagePublish: 'google_test'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: 'd97993aa-c244-425a-9062-763432b37e21'
        versionOption: 'patch'
        packagePublishDescription: 'google test library'
        verbosity: 'Information'


- stage: Test
  jobs:
  - job: job_download_artifact
    displayName: 'download artifacts'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - download: current
      artifact: google_test
      displayName: 'download google_test from Azure  pipeline artifacts'
    - task: UniversalPackages@0
      inputs:
        command: 'download'
        downloadDirectory: '$(System.DefaultWorkingDirectory)'
        feedsToUse: 'internal'
        vstsFeed: 'd97993aa-c244-425a-9062-763432b37e21'
        vstsFeedPackage: '742ea6a7-edef-46d5-a1d0-663a3fa81146'
        vstsPackageVersion: '0.0.1'
        verbosity: 'Information'
