# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

name: demo_pipeline

variables:
  var1: value1

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: job_build_gtest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CMake@1
      inputs:
        workingDirectory: 'cmake_build'
        cmakeArgs: '-DCMAKE_BUILD_TYPE=Release -DBUILD_GMOCK=OFF -DCMAKE_INSTALL_PREFIX=release ..'

    - bash: 'make -j8 VERBOSE=1'
      workingDirectory:  'cmake_build'
      failOnStderr: true
      
    - bash: 'make install'
      workingDirectory:  'cmake_build'
      failOnStderr: true

    - publish: $(Build.SourcesDirectory)/cmake_build/release
      artifact: google_test

- stage: Test
  jobs:
  - job: job_download_artifact
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - download: current
      artifact: google_test
